[build]
builder = "DOCKERFILE"
dockerfilePath = "final_build/saas_build/apps/api/Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
