apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myschoolapp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains";
spec:
  tls:
    - hosts:
        - myschoolapp.pk
        - api.myschoolapp.pk
      secretName: myschoolapp-tls
  rules:
    - host: myschoolapp.pk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myschoolapp-web-svc
                port:
                  number: 80
    - host: api.myschoolapp.pk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myschoolapp-api-svc
                port:
                  number: 80
